### ISSUE TITLE
No bootstrap script added to console app project in VS 2015

### ISSUE THREAD

**Issue by latkin** [TahaHachana/FsPlot#7]
I have an F# 4.0 console app project in VS 2015 preview.  Added FsPlot 0.6.6 via GUI NuGet wizard.

I do not see any .fsx scripts added to my project, as documented [here](http://tahahachana.github.io/FsPlot/).

Not sure if this is out-of-date docs, a bug in the package, or if I'm doing something wrong.

![image](https://cloud.githubusercontent.com/assets/5943573/5793977/fe9565e0-9f0e-11e4-8eb0-592f8ff503dd.png)

**Comment by TahaHachana** [comment]
Hi Lincoln, I noticed that other packages that include bootstrapping scripts place it in the package folder instead of adding it to the project (FSharp.Charting and MBrace for example) so I considered that a best practice and followed them so you need to reference it from there (#load "../packages/FsPlot.0.6.6/FsPlotBootstrap.fsx").

I also suggest checking out [XPlot](http://tahahachana.github.io/XPlot/), a sister project that circumvents the lack of configuration support. There is only a Google Charts package for now but I plan to add more JS plotting libraries.

**Comment by latkin** [comment]
That explains it, thank you. Not being familiar with this convention, I didn't think to look there. It might be nice to mention this in the docs.
